# Define the API version for the Kubernetes resource.
apiVersion: v1
# Specify the type of Kubernetes resource being created, in this case, a Secret.
kind: Secret
# Metadata includes information about the resource, like its name and labels.
metadata:
  # Name of the Secret resource.
  name: mongo-secret
# Type of the Secret. "Opaque" is a generic type for arbitrary secret data.
type: Opaque
# Data section contains base64-encoded key-value pairs that will be stored securely in the Secret.
data:
  # Base64-encoded value representing the MongoDB username.
  mongo-user: base64-encoded-username
  # Base64-encoded value representing the MongoDB password.
  mongo-password: base64-encoded-password